In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.tree import DecisionTreeClassifier , plot_tree
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , mean_absolute_error , r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import plotly.express as px
import plotly.io as pio
pio.renderers.default='notebook'

In [14]:
df = pd.read_csv('diabetes.csv')
df = df.dropna()

In [15]:
x = df.drop(['Outcome'] , axis=1) 
y = df['Outcome']

x_train , x_test , y_train , y_test = train_test_split( x , y , test_size=0.2 , random_state=42)
from sklearn.svm import SVC
svm = SVC(C=1)
svm.fit(x_train , y_train)
y_pred = svm.predict(x_test)
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.78      0.88      0.83        99
           1       0.72      0.56      0.63        55

    accuracy                           0.77       154
   macro avg       0.75      0.72      0.73       154
weighted avg       0.76      0.77      0.76       154

In [16]:
df = pd.read_csv('Teen_Mental_Health_Dataset.csv')

In [17]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [18]:
x=pd.get_dummies(df.drop(['depression_label'],axis=1))
y=df['depression_label']
t=[0.05, 0.10, 0.15, 0.20, 0.25]
d = {"model":[] , "acc":[] , "test":[]}
for i in t:
    x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=i , random_state=42)
    
    d['model'].append('knn')
    d['test'].append(i)
    knn = KNeighborsClassifier(n_neighbors=29)
    knn.fit(x_train,y_train)
    d['acc'].append(accuracy_score(y_test , knn.predict(x_test)))

    d['model'].append('DecisionTree')
    d['test'].append(i)
    dt=DecisionTreeClassifier(criterion='entropy' , max_depth=4 , random_state=42)
    dt.fit(x_train , y_train)
    d['acc'].append(accuracy_score(y_test , dt.predict(x_test)))

    d['model'].append('Random Forest Classifier')
    d['test'].append(i)
    rfc = RandomForestClassifier(n_estimators=100 , max_depth=4 , random_state=42)
    rfc.fit(x_train , y_train)
    d['acc'].append(accuracy_score(y_test , rfc.predict(x_test)))

    d['model'].append('Support Vector Machine')
    d['test'].append(i)
    svm = SVC(C=10 , kernel='rbf' , random_state=42)
    svm.fit(x_train,y_train)
    d['acc'].append(accuracy_score(y_test , svm.predict(x_test)))
new = pd.DataFrame(d)
print(new)

                       model       acc  test
0                        knn  0.933333  0.05
1               DecisionTree  1.000000  0.05
2   Random Forest Classifier  0.933333  0.05
3     Support Vector Machine  0.950000  0.05
4                        knn  0.958333  0.10
5               DecisionTree  1.000000  0.10
6   Random Forest Classifier  0.958333  0.10
7     Support Vector Machine  0.975000  0.10
8                        knn  0.972222  0.15
9               DecisionTree  1.000000  0.15
10  Random Forest Classifier  0.972222  0.15
11    Support Vector Machine  0.983333  0.15
12                       knn  0.975000  0.20
13              DecisionTree  1.000000  0.20
14  Random Forest Classifier  0.975000  0.20
15    Support Vector Machine  0.983333  0.20
16                       knn  0.973333  0.25
17              DecisionTree  0.996667  0.25
18  Random Forest Classifier  0.973333  0.25
19    Support Vector Machine  0.983333  0.25

In [26]:
px.line(data_frame=new, x='test' ,y='acc' , color='model')

In [33]:
result = new.groupby('model')['acc'].max().reset_index()
px.bar(data_frame=result , x='model',y='acc')

In [60]:
from sklearn.preprocessing import PolynomialFeatures
df = pd.read_csv('created_house_price_prediction.csv')
df = df.dropna()
x = pd.get_dummies(df.drop(['Price'] , axis=1))
y= df['Price']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)
mse=[]
d={'degree':[] , 'r2':[]}

for i in range(1,6):
    d['degree'].append(i)
    poly = PolynomialFeatures(degree=i)
    x_train_poly = poly.fit_transform(x_train)
    x_test_poly = poly.transform(x_test)

    model = LinearRegression()
    model.fit(x_train_poly , y_train)
    y_pred = model.predict(x_test_poly)
    
    mse.append(mean_squared_error(y_test , y_pred))
    d['r2'].append(r2_score(y_test , y_pred))
d= pd.DataFrame(d)
m = d['r2'].max()
print(d[d['r2']==m]['degree'])

4    5
Name: degree, dtype: int64

In [64]:
test_size=[0.05, 0.10, 0.15, 0.20, 0.25]
d={'model':[],'test_size':[] , 'r2':[],"mse":[]}

for i in test_size:
    x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=i , random_state=42)
    d['test_size'].append(i)
    d['model'].append('Linear Regression')
    model = LinearRegression()
    model.fit(x_train , y_train)
    y_pred = model.predict(x_test)
    d['mse'].append(mean_squared_error(y_test , y_pred))
    d['r2'].append(r2_score(y_test , y_pred))

    d['test_size'].append(i)
    d['model'].append('Polynomial Regression')
    poly = PolynomialFeatures(degree=5)
    x_train_poly = poly.fit_transform(x_train)
    x_test_poly = poly.transform(x_test)

    model = LinearRegression()
    model.fit(x_train_poly , y_train)
    y_pred = model.predict(x_test_poly)
    
    d['mse'].append(mean_squared_error(y_test , y_pred))
    d['r2'].append(r2_score(y_test , y_pred))
d = pd.DataFrame(d)

In [65]:
d

                   model  test_size        r2           mse
0      Linear Regression       0.05  0.268646  5.655044e+14
1  Polynomial Regression       0.05  0.935609  4.978899e+13
2      Linear Regression       0.10  0.178949  4.047876e+14
3  Polynomial Regression       0.10  0.918805  4.003019e+13
4      Linear Regression       0.15  0.230288  4.316472e+14
5  Polynomial Regression       0.15  0.924259  4.247488e+13
6      Linear Regression       0.20  0.214250  4.011141e+14
7  Polynomial Regression       0.20  0.922892  3.936265e+13
8      Linear Regression       0.25  0.178664  3.994572e+14
9  Polynomial Regression       0.25  0.920735  3.855058e+13

In [73]:
px.line(data_frame=d , x='test_size' , y='r2' , color='model')

In [74]:
px.line(data_frame=d , x='test_size' , y='mse' , color='model')

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error , mean_absolute_error , r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier , plot_tree
from sklearn.ensemble import RandomForestClassifier